"""Synthetic findings used only to exercise the ENS mapping engine."""
from app.models import Finding, FindingType


def mapping_fixtures():
    """Same shapes the old stubs produced, marked as sample for the mapping tests."""
    return [
        Finding(
            finding_type=FindingType.SMB_SIGNING_DISABLED,
            title="[TEST] SMB signing no requerido",
            target="host.example.test",
            detail="Firma SMB no requerida.",
            evidence="RequireSigning=False",
            source_module="enumeration.smb",
            subtype="not_required",
            is_sample=True,
        ),
        Finding(
            finding_type=FindingType.KERBEROASTING,
            title="[TEST] Cuenta de servicio kerberoasteable (RC4)",
            target="svc_sql@example.test",
            detail="SPN con RC4.",
            evidence="etype 23",
            source_module="enumeration.kerberos",
            subtype="rc4",
            is_sample=True,
        ),
        Finding(
            finding_type=FindingType.ASREP_ROASTING,
            title="[TEST] Cuenta sin pre-autenticación Kerberos",
            target="user@example.test",
            detail="DONT_REQUIRE_PREAUTH.",
            evidence="UAC 0x400000",
            source_module="enumeration.kerberos",
            subtype="dont_require_preauth",
            is_sample=True,
        ),
        Finding(
            finding_type=FindingType.UNCONSTRAINED_DELEGATION,
            title="[TEST] Delegación no restringida",
            target="APP01$@example.test",
            detail="TRUSTED_FOR_DELEGATION.",
            evidence="UAC 0x80000",
            source_module="enumeration.delegation",
            is_sample=True,
        ),
        Finding(
            finding_type=FindingType.CONSTRAINED_RBCD_DELEGATION,
            title="[TEST] RBCD escribible",
            target="FILE02$@example.test",
            detail="ACL GenericWrite.",
            evidence="GenericWrite",
            source_module="enumeration.delegation",
            subtype="rbcd_writable",
            is_sample=True,
        ),
        Finding(
            finding_type=FindingType.EXCESSIVE_PRIVILEGES,
            title="[TEST] Domain Admins",
            target="Group: Domain Admins",
            detail="Miembros adicionales.",
            evidence="member",
            source_module="enumeration.delegation",
            is_sample=True,
        ),
        Finding(
            finding_type=FindingType.ADCS_ESC,
            title="[TEST] ESC1",
            target="Template: Test @ test-CA",
            detail="ESC1.",
            evidence="ESC1",
            source_module="enumeration.adcs",
            subtype="ESC1",
            is_sample=True,
        ),
        Finding(
            finding_type=FindingType.ADCS_ESC,
            title="[TEST] ESC6",
            target="CA: test-CA",
            detail="ESC6.",
            evidence="ESC6",
            source_module="enumeration.adcs",
            subtype="ESC6",
            is_sample=True,
        ),
        Finding(
            finding_type=FindingType.ADCS_ESC,
            title="[TEST] ESC8",
            target="http://ca.test/certsrv",
            detail="ESC8 web enrollment.",
            evidence="ESC8",
            source_module="enumeration.adcs",
            subtype="ESC8",
            is_sample=True,
        ),
    ]
